// Canonical company / school options for the onboarding combobox. The point is
// normalization for matching later: two people typing "Google" and "Google LLC"
// should land on the same canonical string. This is a starter set of the most
// common employers/schools; free entry is still allowed for anything not here,
// and the list can be expanded from an open dataset (e.g. the Hipo university
// list) or replaced with an autocomplete API without changing the component.

export const COMPANY_OPTIONS: string[] = [
  "Google",
  "Meta",
  "Amazon",
  "Apple",
  "Microsoft",
  "Netflix",
  "Nvidia",
  "OpenAI",
  "Anthropic",
  "Tesla",
  "Stripe",
  "Airbnb",
  "Uber",
  "Lyft",
  "DoorDash",
  "Instacart",
  "Coinbase",
  "Robinhood",
  "Plaid",
  "Ramp",
  "Brex",
  "Databricks",
  "Snowflake",
  "Salesforce",
  "Oracle",
  "SAP",
  "IBM",
  "Intel",
  "AMD",
  "Qualcomm",
  "Cisco",
  "Adobe",
  "Atlassian",
  "Shopify",
  "Block",
  "PayPal",
  "Palantir",
  "Snap",
  "Pinterest",
  "Reddit",
  "Discord",
  "Spotify",
  "Figma",
  "Notion",
  "Linear",
  "Vercel",
  "GitHub",
  "GitLab",
  "Cloudflare",
  "Datadog",
  "Twilio",
  "Segment",
  "HubSpot",
  "Zoom",
  "Slack",
  "Dropbox",
  "Box",
  "Asana",
  "Airtable",
  "Retool",
  "Rippling",
  "Gusto",
  "Deel",
  "Scale AI",
  "Hugging Face",
  "Perplexity",
  "Mistral AI",
  "Cohere",
  "Roblox",
  "Unity",
  "Epic Games",
  "McKinsey & Company",
  "Boston Consulting Group",
  "Bain & Company",
  "Deloitte",
  "PwC",
  "EY",
  "KPMG",
  "Accenture",
  "Goldman Sachs",
  "Morgan Stanley",
  "JPMorgan Chase",
  "Citadel",
  "Jane Street",
  "Two Sigma",
  "Bridgewater Associates",
  "Sequoia Capital",
  "Andreessen Horowitz",
  "Y Combinator",
  "First Round Capital",
  "Founders Fund",
  "Greylock",
  "Accel",
];

export const SCHOOL_OPTIONS: string[] = [
  "Stanford University",
  "Massachusetts Institute of Technology",
  "Harvard University",
  "University of California, Berkeley",
  "California Institute of Technology",
  "Carnegie Mellon University",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "Cornell University",
  "Brown University",
  "Dartmouth College",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "Johns Hopkins University",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of Southern California",
  "New York University",
  "University of Michigan",
  "University of Illinois Urbana-Champaign",
  "Georgia Institute of Technology",
  "University of Texas at Austin",
  "University of Washington",
  "University of Wisconsin-Madison",
  "University of Waterloo",
  "University of Toronto",
  "Purdue University",
  "University of Maryland",
  "Rice University",
  "Vanderbilt University",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "Boston University",
  "Northeastern University",
  "University of California, Davis",
  "University of California, Irvine",
  "University of Colorado Boulder",
  "Arizona State University",
  "Pennsylvania State University",
  "Ohio State University",
  "University of Florida",
  "Texas A&M University",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "London School of Economics",
  "ETH Zurich",
  "National University of Singapore",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Tsinghua University",
  "Peking University",
  "University of Tokyo",
  "McGill University",
];
